name: test psfunc

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Cache
      #id: cache
      #uses: actions/cache@v1
      #with:
        #path: C:\vcpkg\installed
        #key: 123456
    #- name: install dependencies
      #if: steps.cache.outputs.cache-hit != 'true'
      #run: |
        #vcpkg install zlib
    #- name: show installed
      #run: |
        #cd $env:VCPKG_INSTALLATION_ROOT\installed
        #dir
      - name: show inno setup
        id: ss
        run: |
          [string]$env:tag = '${{ github.ref }}'.Substring('${{ github.ref }}'.LastIndexOf('/') + 1)
          echo "::set-output name=ref::$env:tag"
          
      - name: sshow
        run: |
          echo '${{ steps.ss.outputs.ref }}'
          
      - name: uploadRelease
        id: uploadRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ env.GITHUB_WORKSPACE }}
          asset_path: ./${{ env.GITHUB_WORKSPACE }}.zip
          asset_name: ${{ env.packageName }}.zip
          asset_content_type: application/zip
