name: test psfunc

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Cache
      #id: cache
      #uses: actions/cache@v1
      #with:
        #path: C:\vcpkg\installed
        #key: 123456
    #- name: install dependencies
      #if: steps.cache.outputs.cache-hit != 'true'
      #run: |
        #vcpkg install zlib
    #- name: show installed
      #run: |
        #cd $env:VCPKG_INSTALLATION_ROOT\installed
        #dir
      - name: show inno setup
        id: ss
        run: |
          echo "::set-output name=ref::${{ github.ref }}.Substring(${{ github.ref }}.LastIndexOf('/') + 1)"
          
      - name: sshow
        run: |
          echo ${{ steps.ss.outputs.ref }}
