name: check pull request

on: 
  pull_request:
    branches:
      - '**'
    type: [opened, reopened]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
       
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: .
